version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: /docker/Dockerfile
    container_name: backend-api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/blog_db
    depends_on:
      - mongo
    networks:
      - backend_network

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_network

volumes:
  mongo_data:

networks:
  backend_network:
    driver: bridge
